#!/usr/bin/env bash

set -eo pipefail

# ls -la /data

mkdir /data/pyapps
mkdir /data/pyapps/media
ls -la /data/pyapps

python ./manage.py collectstatic --noinput

python ./manage.py makemigrations --noinput

python ./manage.py migrate --noinput

#python ./manage.py makesuperuser


